language: cpp
sudo: false

compiler: 
 - gcc
  
install: 
 - apt-get install libboost-all-dev

script:
 - mkdir build 
 - cd build 
 - cmake -DCMAKE_BUILD_TYPE=Debug .. 
 - make -j 
 - make doc 
 - make test 
 - make install
 
notifications:
  email: false
 
