language: cpp
sudo: false

os:
  - linux
#  - osx https://docs.travis-ci.com/user/multi-os/

compiler: 
 - gcc
  
addons:
  apt:
    packages:
      - cmake
      - libboost-all-dev
    sources:
      - george-edison55/cmake-3.x

script:
 - cmake --version
 - mkdir build 
 - cd build 
 - cmake -DCMAKE_BUILD_TYPE=Debug .. 
 - make -j 
 - make doc 
 - make test 
 - make install
 
notifications:
  email: false
 
